I"c<!--more-->

<!-- CreateTime:2019/10/7 12:21:19 -->

<!-- csdn -->

<p>We can write a class that inherits the StylusPlugIn. And this class can get the touch event fast in stylus input thread in the overwrite method, such as <code class="language-plaintext highlighter-rouge">OnStylusDown</code> and the OnStylusUp method. The <em>Stylus Input</em> thread is backgroud thread. As we all know, any exception thrown in a background thread will destroy the application. We are hard to catch the background thread and recover this thread. Though we can use <code class="language-plaintext highlighter-rouge">AppDomain.CurrentDomain.UnhandledException</code> and add <code class="language-plaintext highlighter-rouge">&lt;legacyUnhandledExceptionPolicy enabled="1"/&gt; </code> to app.config to catch it.</p>

<p>The <code class="language-plaintext highlighter-rouge">StylusPlugIn</code> can be inherited and we can overwrite the method. And we can not stop our friend add his code in the method, such as OnStylusDown method. But we may not enough careful in our code that the code will throw the exception in unexpected in the OnStylusDown method. And the exception will break the stylus input thread and the WPF application will stop responding the touch. And we can not do something to recover the touch responding. Just like this code. The code will break the Stylus Input thread.</p>

<div class="language-csharp highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">public</span> <span class="k">partial</span> <span class="k">class</span> <span class="nc">MainWindow</span> <span class="p">:</span> <span class="n">Window</span>
<span class="p">{</span>
    <span class="k">public</span> <span class="nf">MainWindow</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="nf">InitializeComponent</span><span class="p">();</span>
        <span class="n">StylusPlugIns</span><span class="p">.</span><span class="nf">Add</span><span class="p">(</span><span class="k">new</span> <span class="nf">Foo</span><span class="p">());</span>
    <span class="p">}</span>
<span class="p">}</span>

<span class="k">public</span> <span class="k">class</span> <span class="nc">Foo</span> <span class="p">:</span> <span class="n">StylusPlugIn</span>
<span class="p">{</span>
    <span class="c1">/// &lt;inheritdoc /&gt;</span>
    <span class="k">protected</span> <span class="k">override</span> <span class="k">void</span> <span class="nf">OnStylusDown</span><span class="p">(</span><span class="n">RawStylusInput</span> <span class="n">rawStylusInput</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">Exception</span><span class="p">();</span>
    <span class="p">}</span>
<span class="p">}</span>
</code></pre></div></div>

<p>The OnStylusDown running in Stylus Input thread and if some friend throws any exceptions that will break the thread. And the application will stop responding touch.</p>

<p>Of course, the actual situation may be more complicated. Maybe some of my friends just didn’t realize that the code he wrote was unstable. But add <code class="language-plaintext highlighter-rouge">try catch</code> to all the method is an evil code.</p>

<p>But I do not think we can throw any unintended exceptions in StylusPlugIn.</p>

<p>See <a href="https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.stylusplugins.stylusplugin?view=netframework-4.8">StylusPlugIn Class (System.Windows.Input.StylusPlugIns)</a></p>

<blockquote>
  <p>If you use a StylusPlugIn inside a control, you should test the plug-in and control extensively to make sure they do not throw any unintended exceptions.</p>
</blockquote>

<p>See <a href="https://msdn.microsoft.com/en-us/data/ms749105(v=vs.80)">Intercepting Input from the Stylus</a></p>

<blockquote>
  <p>If a StylusPlugIn throws or causes an exception, the application will close. You should thoroughly test controls that consume a StylusPlugIn and only use a control if you are certain the StylusPlugIn will not throw an exception.</p>
</blockquote>

<p>Just as the document say, we should make sure the code do not throw any unintended exceptions in StylusPlugIn. But actual we are hard to do it in the complex business.</p>

<p>I think it may be a good way that we can catch all the exceptions in the code that fire the StylusPlugIn method.</p>

<p>We are making a full-screen touch application and the user can only control the machine by touch input. If the WPF application stops responding touch, the user can not do something except reboot.</p>

<p>All the demo code in <a href="https://github.com/lindexi/lindexi_gd/tree/4f1cda37f1a6eb4fc88fa404b104cbf9b29b365e/KihemjaibeaNafebahearjece">github</a></p>

<p><a href="https://github.com/dotnet/wpf/issues/1037">WPF will break when an exception be throw in the StylusPlugIn · Issue #1037 · dotnet/wpf</a></p>
:ET